use PS41827_QLDA;
GO
--BAI 1
--Chỉnh sửa cột thời trong bảng PhanCong với dữ liệu  
SELECT *,
CAST(THOIGIAN AS VARCHAR) AS DOITHOIGIAN,
CONVERT(VARCHAR , THOIGIAN) AS CONVERTTHG
FROM PHANCONG
--Với mỗi đề án, liệt kê tên đề án và tổng số giờ làm việc một tuần của tất cả các nhân viên tham dự đề án đó.
SELECT MADA, SUM(THOIGIAN)
FROM PHANCONG
GROUP BY MADA
--Xuất định dạng “tổng số giờ làm việc” kiểu decimal với 2 số thập phân.
SELECT MADA, CAST(SUM(THOIGIAN)AS decimal(5,2))
FROM PHANCONG
GROUP BY MADA
-- VARCHAR
SELECT MADA, CAST(SUM(THOIGIAN)AS VARCHAR)
FROM PHANCONG
GROUP BY MADA
-- XUAT KIEU CONVERT
SELECT MADA, CONVERT(decimal(5,2), SUM(THOIGIAN))
FROM PHANCONG
GROUP BY MADA

DECLARE @THONGKEDA TABLE
(MADA VARCHAR(10),SUMTG FLOAT)
INSERT INTO @THONGKEDA
SELECT MADA, SUM(THOIGIAN) AS SUMTG
FROM PHANCONG
GROUP BY MADA
SELECT TK.*, DA.TENDEAN
FROM @THONGKEDA TK JOIN DEAN DA ON TK.MADA=DA.MADA
-- XUAT CAST
-- KIEU DECIMAL
SELECT DA.TENDEAN,CAST(SUMTG AS decimal(5,2))
FROM @THONGKEDA TK JOIN DEAN DA ON TK.MADA=DA.MADA
-- KIEU VARCHAR
SELECT DA.TENDEAN,CAST(SUMTG AS VARCHAR)
FROM @THONGKEDA TK JOIN DEAN DA ON TK.MADA=DA.MADA
--XUAT CONVERT
--KIEU DECIMAL
SELECT DA.TENDEAN, CONVERT(decimal(5,2),SUMTG)
FROM @THONGKEDA TK JOIN DEAN DA ON TK.MADA=DA.MADA
--KIEU VARCHAR
SELECT DA.TENDEAN, CONVERT(varchar,SUMTG)
FROM @THONGKEDA TK JOIN DEAN DA ON TK.MADA=DA.MADA

--Với mỗi phòng ban, liệt kê tên phòng ban và lương trung bình của những nhân viên làm việc cho phòng ban đó.
DECLARE @THONGKELUONG TABLE
(MAPHG VARCHAR(10),AVGLUONG FLOAT)
INSERT INTO @THONGKELUONG
SELECT PHG, AVG(LUONG) AS AVGLUONG
FROM NHANVIEN
GROUP BY PHG
SELECT TK.*, PB.TENPHG
FROM @THONGKELUONG TK JOIN PHONGBAN PB ON TK.MAPHG=PB.MAPHG

--XUAT CAST
-- KIEU DECIMAL
SELECT PB.TENPHG, CAST(AVGLUONG AS decimal(10,2))
FROM @THONGKELUONG TK JOIN PHONGBAN PB ON TK.MAPHG=PB.MAPHG
--KIEU VARCHAR
SELECT PB.TENPHG, CAST(AVGLUONG AS varchar)
FROM @THONGKELUONG TK JOIN PHONGBAN PB ON TK.MAPHG=PB.MAPHG
--XUAT CONVERT
--KIEU DECIMAL
SELECT PB.TENPHG, CONVERT(decimal(10,2),AVGLUONG)
FROM @THONGKELUONG TK JOIN PHONGBAN PB ON TK.MAPHG=PB.MAPHG
--KIEU VARCHAR
SELECT PB.TENPHG, CONVERT(varchar,AVGLUONG)
FROM @THONGKELUONG TK JOIN PHONGBAN PB ON TK.MAPHG=PB.MAPHG

--BAI 2
--Với mỗi đề án, liệt kê tên đề án và tổng số giờ làm việc một tuần của tất cả các nhân viên 
--tham dự đề án đó.
DECLARE @TONGHOPDA TABLE
(MADA VARCHAR(10),SUMTG FLOAT)
INSERT INTO @TONGHOPDA
SELECT MADA, SUM(THOIGIAN) AS SUMTG
FROM PHANCONG
GROUP BY MADA
SELECT TH.*, DA.TENDEAN
FROM @TONGHOPDA TH JOIN DEAN DA ON TH.MADA=DA.MADA

--Hàm CEILING
SELECT DA.TENDEAN,CEILING(SUMTG) AS TONG_TG
FROM @TONGHOPDA TH JOIN DEAN DA ON TH.MADA=DA.MADA

-- Hàm FLOOR
SELECT DA.TENDEAN,FLOOR(SUMTG) AS TONG_TG
FROM @TONGHOPDA TH JOIN DEAN DA ON TH.MADA=DA.MADA

--Làm tròn tới 2 chữ số thập phân
SELECT DA.TENDEAN, ROUND(SUMTG,2) AS TONG_TG
FROM @TONGHOPDA TH JOIN DEAN DA ON TH.MADA=DA.MADA

--Cho biết họ tên nhân viên (HONV, TENLOT, TENNV) có mức lương trên mức lương 
--trung bình (làm tròn đến 2 số thập phân) của phòng "Nghiên cứu"
DECLARE @AVG_LUONG_NC FLOAT;
SELECT @AVG_LUONG_NC = ROUND(AVG(LUONG), 2)
FROM NHANVIEN
WHERE PHG = (SELECT MAPHG FROM PHONGBAN WHERE TENPHG = N'Nghiên cứu');
SELECT CONCAT(HONV,' ',TENLOT,' ', TENNV) AS TENNVIEN, LUONG
FROM NHANVIEN
WHERE LUONG > @AVG_LUONG_NC;

--BAI 3
--Danh sách những nhân viên (HONV, TENLOT, TENNV, DCHI) có trên 2 thân nhân
-- Tạo biến bảng lưu MANV có hơn 2 thân nhân
DECLARE @DSNV TABLE (MANV CHAR(9));

-- Thêm nhân viên có hơn 2 thân nhân
INSERT INTO @DSNV
SELECT MA_NVIEN
FROM THANNHAN
GROUP BY MA_NVIEN
HAVING COUNT(*) > 2;

-- Truy vấn danh sách nhân viên với định dạng theo yêu cầu
SELECT 
    UPPER(NV.HONV) AS HONV,
    LOWER(NV.TENLOT) AS TENLOT,
    -- Ký tự 2 viết hoa
    LOWER(LEFT(NV.TENNV,1)) + UPPER(SUBSTRING(NV.TENNV,2,1)) + LOWER(SUBSTRING(NV.TENNV,3,LEN(NV.TENNV))) AS TENNV,
    
    -- Cắt tên đường từ địa chỉ (giả định có dấu phẩy phân cách tên đường với phần sau)
    LTRIM(RTRIM(
        SUBSTRING(
            SUBSTRING(NV.DCHI, CHARINDEX(' ', NV.DCHI) + 1, LEN(NV.DCHI)),
            1,
            CHARINDEX(',', SUBSTRING(NV.DCHI, CHARINDEX(' ', NV.DCHI) + 1, LEN(NV.DCHI)) + ',') - 1
        )
    )) AS DCHI
FROM 
    NHANVIEN NV
JOIN 
    @DSNV DS ON NV.MANV = DS.MANV;

--Cho biết tên phòng ban và họ tên trưởng phòng của phòng ban có đông nhân viên nhất, 
--hiển thị thêm một cột thay thế tên trưởng phòng bằng tên “Fpoly” 
-- Biến lưu MÃ PHÒNG có số nhân viên nhiều nhất
DECLARE @PHONG_MAX CHAR(5);

-- Tìm mã phòng ban có nhiều nhân viên nhất
SELECT TOP 1 @PHONG_MAX = PHG
FROM NHANVIEN
GROUP BY PHG
ORDER BY COUNT(*) DESC;

-- Truy vấn thông tin phòng ban đó
SELECT 
    PB.TENPHG,
    CONCAT(NV.HONV, ' ', NV.TENLOT, ' ', NV.TENNV) AS HOTEN_TRUONGPHONG,
    'Fpoly' AS TEN_THAY_THE
FROM 
    PHONGBAN PB
JOIN 
    NHANVIEN NV ON PB.TRPHG = NV.MANV
WHERE 
    PB.MAPHG = @PHONG_MAX;


--Bai 4
--Sử dụng các hàm ngày tháng năm 
-- Cho biết các nhân viên có năm sinh trong khoảng 1960 đến 1965. 
SELECT *
FROM NHANVIEN
WHERE YEAR(NGSINH) BETWEEN 1960 AND 1965;

-- Cho biết tuổi của các nhân viên tính đến thời điểm hiện tại. 
SELECT  MANV,HONV,TENLOT,TENNV,NGSINH,DATEDIFF(YEAR, NGSINH, GETDATE()) AS TUOI
FROM NHANVIEN;

-- Dựa vào dữ liệu NGSINH, cho biết nhân viên sinh vào thứ mấy. 
SELECT MANV,HONV,TENLOT,TENNV,NGSINH,DATENAME(WEEKDAY, NGSINH) AS THU_SINH
FROM NHANVIEN;

-- Cho biết số lượng nhân viên, tên trưởng phòng, ngày nhận chức trưởng phòng và ngày 
--nhận chức trưởng phòng hiển thi theo định dạng dd-mm-yy (ví dụ 25-04-2019)
SELECT PB.MAPHG,PB.TENPHG,COUNT(NV.MANV) AS SO_LUONG_NV,
    CONCAT(TP.HONV, ' ', TP.TENLOT, ' ', TP.TENNV) AS TEN_TRUONG_PHONG,
    FORMAT(PB.NG_NHANCHUC, 'dd-MM-yy') AS NGAY_NHAN_CHUC
FROM 
    PHONGBAN PB
LEFT JOIN NHANVIEN NV ON NV.PHG = PB.MAPHG
JOIN NHANVIEN TP ON TP.MANV = PB.TRPHG
GROUP BY 
    PB.MAPHG, PB.TENPHG, TP.HONV, TP.TENLOT, TP.TENNV, PB.NG_NHANCHUC;
