
USE PS41827_QLDA;
--1. Cho biêt nhân viên có lương cao nhất 
DECLARE @MAXLUONG FLOAT
SELECT @MAXLUONG = MAX(LUONG)
FROM NHANVIEN
PRINT N'LƯƠNG CAO NHẤT LÀ: ' + CAST(@MAXLUONG AS VARCHAR)
SELECT *
FROM NHANVIEN
WHERE LUONG = @MAXLUONG

--2. Cho biết họ tên nhân viên (HONV, TENLOT, TENNV) có mức lương 
--trên mức lương trung bình của phòng "Nghiên cứu” 
DECLARE @LUONGTB FLOAT
DECLARE @MAPHONG INT
SELECT @LUONGTB=AVG(LUONG)FROM NHANVIEN
SELECT @MAPHONG = MAPHG FROM PHONGBAN
-- THỰC THI
SELECT MANV,TENLOT,TENNV,LUONG
FROM NHANVIEN
WHERE LUONG > @LUONGTB

--3. Với các phòng ban có mức lương trung bình trên 30,000, liệt kê tên 
--phòng ban và số lượng nhân viên của phòng ban đó. 
--LƯƠNG TB
SELECT AVG(LUONG) FROM NHANVIEN
SELECT PHG, COUNT(MANV) AS SLNV
FROM NHANVIEN
GROUP BY PHG
--BIẾN BẢNG
DECLARE @THONGKELUONGTBLONHON30 TABLE
(MAPB INT, SLNV INT, LUONGTB FLOAT)
INSERT INTO @THONGKELUONGTBLONHON30
SELECT PHG, COUNT(MANV) AS SLNV, AVG(LUONG)
FROM NHANVIEN
GROUP BY PHG
HAVING AVG(LUONG) >=30000

--4. Với mỗi phòng ban, cho biết tên phòng ban và số lượng đề án mà 
--phòng ban đó chủ trì 
 DECLARE @THONGTIN TABLE
 (TENPB VARCHAR(50), SLDA INT)
 INSERT INTO @THONGTIN
 SELECT TENPHG, COUNT(MADA) as SLDA
 FROM PHONGBAN PB JOIN DEAN DA ON PB.MAPHG=DA.PHONG
 GROUP BY TENPHG
 SELECT * FROM @THONGTIN

 --5. Diện tích hình chữ nhật
 DECLARE @DAI INT
 DECLARE @RONG INT
 DECLARE @S INT
 SET @DAI = 6
 SET @RONG =8
 SET @S = @DAI * @RONG
 PRINT N'Diện tích hình chữ nhật: ' + cast(@s as varchar)

