
use master
go
--Y4
-- Tạo LOGIN cấp server
CREATE LOGIN admin_QuanPS41827 WITH PASSWORD = 'Admin@123', DEFAULT_DATABASE = QLNHATRO_QuanPS41827, CHECK_POLICY = OFF;
CREATE LOGIN user_QuanPS41827  WITH PASSWORD = 'User@123',  DEFAULT_DATABASE = QLNHATRO_QuanPS41827, CHECK_POLICY = OFF;
GO

-- Gắn USER tương ứng trong database QLNHATRO_QuanPS41827
USE QLNHATRO_QuanPS41827;
GO

CREATE USER admin_QuanPS41827 FOR LOGIN admin_QuanPS41827;
CREATE USER user_QuanPS41827  FOR LOGIN user_QuanPS41827;
GO

--Phân quyền
--Người dùng quản trị
ALTER ROLE db_owner ADD MEMBER admin_QuanPS41827;
GO

--Người dùng thông thường
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.LOAINHA TO user_QuanPS41827;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.NGUOIDUNG TO user_QuanPS41827;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.NHATRO TO user_QuanPS41827;
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.DANHGIA TO user_QuanPS41827;

-- Cho phép gọi tất cả SP và Function
GRANT EXECUTE TO user_QuanPS41827;
GO





